### PR TITLE
Prevent adding underscores to URL

### PR DESCRIPTION
**Pull request by ihor-sviziev**
This change changing `$.get(url,...)` to `$.get({url: url, cache: true},...)`.

As magento 2.2 by default preventing caching ajax requests in https://github.com/magento/magento2/blob/2.2-develop/lib/web/mage/bootstrap.js#L14 - jquery adds special underscore to requests URL, as result - Magento FPC doesn't work as expected.
URL example: http://myhost.com/category.html?p=1&_=111 (where _=111 is dynamically changes)

Current lib version that is used - not allowing us to define custom ajaxOptions (as described in https://infiniteajaxscroll.com/docs/events.html#load). Another option - upgrade to version where it's allowed to modify

### CODE REVIEW

**Comment by gsomoza** [comment]
I would prefer to avoid making custom changes to the IAS library, so we can just bundle it and not worry about migrating the changes to new versions.

So the best solution in this case would probably be to upgrade to a newer version of the IAS library that allows us to make this change "outside" (on our end). We would happily merge a PR that does that!

If you agree then let's close this one, let me know when ready for that.

**Comment by ihor-sviziev** [comment]
@gsomoza I agree with you, but definitely it will take more time to upgrade to new version.

**Comment by gsomoza** [comment]
Do you already have an idea of which version we would have to migrate to? is it a new major version?

**Comment by ihor-sviziev** [comment]
@gsomoza I think better idea to move to lasest stable verstion, currently it's 2.3.1

**Pull request closed without merging**
