### PR TITLE
Fix Uncaught TypeError: $(...).catalogAddToCart is not a function issue

### PR DESCRIPTION
**Pull request by ihor-sviziev**
This PR fixes issue described in #24

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@gsomoza could you review this PR?

**Comment by gsomoza** [comment]
The code looks good and makes sense too. Were you able to confirm this against a clean M2 installation with this plugin? If so then we'll merge directly (otherwise we'll have to test that ourselves, which might take a bit).

**Comment by ihor-sviziev** [comment]
@gsomoza sure, I just installed module and on category page got this issue (merge of js is disabled, developer mode enabled)

**Comment by gsomoza** [comment]
Ok but it sound like we'll have to quickly test on a clean Magento install just in case. I'm 99% sure it will work, but we need to do that just to be 100% sure.

Thanks a lot for the pull request!  We'll try to merge it ASAP.

**Comment by gsomoza** [comment]
@damian-pastorini could you please assign this to Juan or Vitaly? (or if you find the time you can do it yourlself if you want)

**Pull request merged**
