### PR TITLE
Hide toolbar by default

### PR DESCRIPTION
**Pull request by ihor-sviziev**
This PR hides toolbar (pagination was hidden in #30, but limit appeared back, it's not needed when infinite scroll is enabled)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
FYI I updated selector for toolbar, because following blocks disappeared:
capture 2018-06-01 at 14 22 35

**Comment by gsomoza** [comment]
@ihor-sviziev I'm a bit worried about merging this and that suddenly a lot of things would change on websites that were relying on the old defaults.

I think the best way to avoid this effect is to create a migration script that will copy the old defaults into the default store config (in the database) – only when upgrading from an older version of the module. 

Is that something you'd be willing to add to your pull request?

The other alternative is to wait with these changes until we release a new major version of the extension. Or if you have any other suggestions let's discuss.

**Comment by ihor-sviziev** [comment]
Hi,

Good idea to add setup upgrade script, but I don't have time for doing that. I don't mind if you'll include it in next major release

**Comment by gsomoza** [comment]
Oops, I ended up bumping major version on the last release anyway and forgot to merge this one (🤦‍♂). I think I might release this one alone with another major bump anyway, but I'll wait a bit to see if any other PRs come in first.

**Pull request merged**
