### PR TITLE
Fix Bundling. Fixes #50 Fixes #39 Fixes #10.

### LINKED ISSUE #10: Multiple issues related to minfication, merging and bundling js
Hey there,

I did a composer based installation in a Magento 2.1.4 system. However, oob there seems to be a problem (maybe related to combine/merge/minify js) with an undefined object

    window.iasConfig is undefined

See everything frontend related here:
https://www.makerdise.com/3d-druck/ersatzteile.html

I just noticed that there are other missing objects related to the window object.

Best
Jan

### LINKED ISSUE #39: IASPagingExtension is not defined issue in Production mode.
Everything is working fine but when we switch into production mode extension is not working. I debug but did not find any issue.
ajaxscroll_issue

### LINKED ISSUE #50: Not working in 2.3+
I tried to get this working in Magento 2.3.2, but it doesn't seem to work. I also tried to change some of the selectors to match other classes, and no such luck.

### PR DESCRIPTION
**Pull request by AntonEvers**
This module uses Infinite Ajax Scroll v2.2.1. All the plugins for
that module (Pagination etc) are not compatible with requireJs because
they are using globals. The only way that this modules JS can access
these globals is by either converting IAS to a requireJs compatible
library or by including the entire file in the infinitescroll.js. This
is a hack, I am aware of that, but until IAS 3.x is available, I think
this at least returns the possiblility to bundle, merge and minify js
again in Magento stores using this plugin.

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
I think that's not a good idea to add library inside file with another library. That's definitely wrong way.

**Comment by gsomoza** [comment]
It's a hack, but I see the reasoning and I think it's valuable. In fact I'm inclined to merge it sooner rather than later, because it addresses well-known issues with the current implementation.

If we release this soon then I'd probably bump major version just to be on the safer side with semver. But an argument could be made that this PR doesn't introduce API changes. @AntonEvers do you think we could release bumping minor instead?

**Comment by gsomoza** [comment]
Any thoughts @AntonEvers ? Otherwise I'll bump major.

**Comment by AntonEvers** [comment]
@gsomoza sorry for the delay. It does add a backward incompatible change, as people could have written patches to the file that is now removed. So major would be justified.

**Comment by gsomoza** [comment]
Well, that would mean patching a minified 3rd-party library, which is questionable anyway. But you're right, I'll bump major.

**Pull request merged**
