### PR TITLE
Change PHP 7 constraint to allow 7.4

### PR DESCRIPTION
**Pull request by pikulsky**
Magento 2.4 requires PHP ~7.4.0 (see https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements-tech.html#php)

### CODE REVIEW

**Comment by gsomoza** [comment]
Thanks @pikulsky – out of curiosity were you able to confirm everything works on PHP 7.4 and Magento 2.4?

**Comment by pikulsky** [comment]
> Thanks @pikulsky – out of curiosity were you able to confirm everything works on PHP 7.4 and Magento 2.4?

Can't confirm: didn't try yet.

**Comment by gsomoza** [comment]
@damian-pastorini could you please QA this when you get a chance?

**Comment by pikulsky** [comment]
@damian-pastorini , @gsomoza , FYI: I've tested it locally, the module works OK in Magent 2.4.0 (PHP 7.4), no issue so far.

**Comment by gsomoza** [comment]
Thanks @pikulsky, merged and releasing soon.

**Pull request merged**
