### PR TITLE
Improved requireJs configuration.

### PR DESCRIPTION
**Pull request by ekalinak**
Added possibility to adjust JS dependencies also in different require-config.js files *( i.e. theme or module )* 

With original code it was not possible.

### CODE REVIEW

**Comment by gsomoza** [comment]
Thanks for the PR. @damian-pastorini can you investigate when you get a chance?

**Comment by gsomoza** [comment]
@ekalinak would this help fix #10 as well by any chance?

**Comment by ekalinak** [comment]
@gsomoza : I can't confirm this at the moment. Installation which I'm working on at the moment is in developer mode. I can give you an update after switching to production mode + turn of JS bundling.

**Comment by gsomoza** [comment]
Ok, thanks anyways

**Comment by gsomoza** [comment]
@damian-pastorini please try to review and merge these changes asap so we can release a new version

**Comment by damian-pastorini** [comment]
Tested and working :+1: 
Thanks @ekalinak !

**Pull request merged**
